FROM golang:1-alpine AS builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o /yt-feed-builder ./cmd/yt-feed-builder/

FROM alpine:3.20
RUN apk add --no-cache ca-certificates tzdata yt-dlp
COPY --from=builder /yt-feed-builder /yt-feed-builder
EXPOSE 8081
ENTRYPOINT ["/yt-feed-builder"]
